### ISSUE TITLE
How does auto redeem work?

### ISSUE THREAD

**Issue by DerMuffin** [sazncode/BingRewards#28] opened 2022-11-02 14:07 UTC
Hey!

Looks like a nice bot. Thanks for your work.

Im wondering how this auto redeem feature work? I need to type in a phone number and type in a code everytime i want to redeem a voucher.

How does this bot handle this kind? How does the script know if i want dollar, Euros or other?

Thanks

Muffin

**Comment by sazncode** [comment] 2022-11-03 14:45
Hello DerMuffin,

The bot was developed within the United States, therefore the bot uses a 1300 points/1 USD conversion for output printing and apprise alerts. We do not know the conversion rate for Euro accounts, as we do not have access to Euro accounts for testing/calculating how many points is the equivalent to a $1 worth. However, I would be happy to add that into the bot if you have access to an Euro Bing account & are willing to give me some more information about the cost of $5 & $10 non-Microsoft/discounted giftcards. 

The bot compares whether the amount of points in an account is equal to or exceeds the amount of points assigned to the goal reward, and attempts an auto-redemption if that is the case. In which case, handling different currency conversion rates aren't necessary for auto-redemption functionality.

Bing Rewards should only require a phone verification once (during the very first redemption), every sequential or future redemption shouldn't prompt you for a phone verification--thus allowing for auto-redemption to work it's magic. However, if a phone verification is required every single redemption for Euro accounts, the feature unfortunately will not work as intended.

Lastly, in order for us to begin implementation of different currency conversion rates, I'd like to ask you for the following information from an Euro account:

- Reward point cost for a $5 Amazon (or other, non-Microsoft/discounted) gift-card.
- Reward points cost for a $10 Gift-card/Reward.

Thank you for your interest!
I look forward to your response.

**Comment by DerMuffin** [comment] 2022-11-04 10:25
5€ Amazon costs 7500 Points
10€ Amazon costs 15000 Points

_"Bing Rewards should only require a phone verification once (during the very first redemption), every sequential or future redemption shouldn't prompt you for a phone verification--thus allowing for auto-redemption to work it's magic. However, if a phone verification is required every single redemption for Euro accounts, the feature unfortunately will not work as intended."_

- Will have a look into this. As far i know its everytime. But i run a lot of Accounts. Might be i only do first orders by now.

Feel free to Ping me if you need any more information

**Comment by sazncode** [comment] 2022-11-04 12:43
Hello again DerMuffin,

Based on your information, Euro based Bing Rewards accounts have a rate of 1500 points/€1.00. Thank you. I have implemented a 'CURRENCY' env variable you can pass 'EURO' or '€' to in-order to receive more accurate output and alerts regarding the value of your Bing Reward points in your currency. We are grateful for international users as yourself assisting in improving our bot.

Unfortunately, if Euro's version of Bing Rewards prompts you for a code every time you attempt to redeem, the bot will be unable to use auto-redemption & you will need to redeem your rewards manually, as the bot cannot automate any kind of phone redemption. Within US accounts, a phone verification is only required during first redemption or locked accounts. If that is not the case for international accounts, sadly it seems the bot will only support US redemption automation as VIOP numbers are restricted to non-verification usage. 

Thank you for your support.
I will be marking this issue as closed. 
If you have any other questions or issues, please feel free to start a new issue.

**Closed by sazncode** 2022-11-04 12:43 UTC
